version: "3.3"

services:
    nginx:
        build:
            context: .
            dockerfile: docker/Nginx.Dockerfile
        ports:
            - 8093:80
        links:
            - fpm
        volumes:
            - ./:/var/www/test-crud
    fpm:
        build:
            context: .
            dockerfile: docker/Fpm.Dockerfile
        volumes:
            - ./:/var/www/test-crud
        links:
            - mysql
        working_dir: /var/www/test-crud
    mysql:
        image: mysql:5.7
        ports:
            - 33061:3306
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=testcrud
